Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -42,21 +42,31 @@ runs:
         set -x
 
         #Set GCP Project ID
-        echo "${{ inputs.application_credentials }}" | base64 --d | printf %s > gcp-credentials.json
+        gcloud config set project ${{ inputs.project_id }}
+
+        #Activate Service Account
+        echo "${{ inputs.application_credentials }}" | base64 --decode > gcp-credentials.json
 
         #gcloud auth activate-service-account --key-file="${{ inputs.application_credentials}}"
+        
         gcloud auth activate-service-account --key-file="gcp-credentials.json"
-        gcloud config set project ${{ inputs.project_id }}
+        
+        
 
         if [ "${{ inputs.command }}" = "rsync" ]; then
           gsutil -m rsync -r -c -d -x "${{ inputs.exclude }}" "${{ inputs.sync_dir_from }}" "${{ inputs.sync_dir_to }}"
-          if [ $? -ne 0 ]; then
-            echo "Syncing failed"
-            exit 1
-          fi
+            if [ $? -ne 0 ]; then
+              echo "Syncing failed"
+              exit 1
+            fi
         elif [ "${{ inputs.command }}" = "cp" ]; then
-          gsutil ${{ inputs.flags }} cp ${{ inputs.source_file }} ${{ inputs.destination_file }}
-        
+          gsutil ${{ inputs.flags }} cp "${{ inputs.source_file }}" "${{ inputs.destination_file }}"
+            if [ $? -ne 0 ]; then
+              echo "Copying failed"
+              exit 1
+            fi
+        fi
+
         echo "Done"
       env:
         GOOGLE_APPLICATION_CREDENTIALS: gcp-credentials.json
